stages:
  - build
  - simulate
  - cleanup

default:
  tags:
  - linux
  - ecu
variables:
  CXX: g++
  BUILD_DIR: build

build:
  stage: build
  script:
    - mkdir -p $BUILD_DIR
    - $CXX ecu1.cpp -o $BUILD_DIR/ecu1
    - $CXX ecu2.cpp -o $BUILD_DIR/ecu2
  artifacts:
    paths:
      - $BUILD_DIR

simulate:
  stage: simulate
  tags:
    - linux
    - ecu
  script:
    - chmod +x setup_netns.sh cleanup.sh
    - sudo ./setup_netns.sh

    # Run ECU2 server in background
    - sudo ip netns exec ecu2 /home/ons/summerInternship2025/ecus_simulation/build/ecu2 > ecu2_output.txt 2>&1 &
    - sleep 1  # wait for server to start

    # Run ECU1 client once
    - sudo ip netns exec ecu1 /home/ons/summerInternship2025/ecus_simulation/build/ecu1 &
    - sleep 2  # give it time to send

    - echo "===== ECU2 Output ====="
    - cat ecu2_output.txt
    - grep "status OK" ecu2_output.txt

  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - ecu2_output.txt

cleanup:
  stage: cleanup
  script:
    - sudo ./cleanup.sh
