stages:
  - setup
  - test

# Step 1: Setup ECU network namespaces
setup_network:
  stage: setup
  script:
    - echo " Running setup script..."
    - chmod +x setup_netns.sh
    - sudo ./setup_netns.sh
  allow_failure: false
  when: on_success

# Step 2: Test communication between ECUs
test_ping:
  stage: test
  tags:
    - linux
    - ecu
  script:
    - echo " Testing communication from ECU1 to ECU2..."
    - sudo ip netns exec ecu1 ping -c 3 10.0.0.2
  allow_failure: false
  when: on_success
