stages:
  - build
  - simulate
  - fault-test
  - summary

default:
  tags:
    - linux
    - ecu

variables:
  BUILD_DIR: build
  CXX: g++

build:
  stage: build
  script:
    - mkdir -p $BUILD_DIR
    - $CXX ecu1.cpp -o $BUILD_DIR/ecu1
    - $CXX ecu2.cpp -o $BUILD_DIR/ecu2
  artifacts:
    paths:
      - $BUILD_DIR

simulate:
  stage: simulate
  script:
    - chmod +x setup_netns.sh cleanup.sh
    - sudo ./setup_netns.sh
    - sudo ip netns exec ecu2 ./$BUILD_DIR/ecu2 > ecu2_output.txt 2>&1 &
    - sleep 1
    - sudo ip netns exec ecu1 ./$BUILD_DIR/ecu1 > /dev/null 2>&1 &
    - sleep 3
  artifacts:
    paths:
      - ecu2_output.txt

# One job per fault
test_block:
  stage: fault-test
  script:
    - sudo ./faults/reset.sh
    - sleep 1
    - bash test/test_block.sh > test/block.log
    - sudo ./faults/reset.sh
  artifacts:
    paths:
      - test/block.log

test_delay:
  stage: fault-test
  script:
    - sudo ./faults/reset.sh
    - sleep 1
    - bash test/test_delay.sh > test/delay.log
    - sudo ./faults/reset.sh
  artifacts:
    paths:
      - test/delay.log

test_loss:
  stage: fault-test
  script:
    - sudo ./faults/reset.sh
    - sleep 1
    - bash test/test_loss.sh > test/loss.log
    - sudo ./faults/reset.sh
  artifacts:
    paths:
      - test/loss.log

test_corrupt:
  stage: fault-test
  script:
    - sudo ./faults/reset.sh
    - sleep 1
    - bash test/test_corrupt.sh > test/corrupt.log
    - sudo ./faults/reset.sh
  artifacts:
    paths:
      - test/corrupt.log

summary:
  stage: summary
  script:
    - chmod +x test/generate_summary.sh
    - ./test/generate_summary.sh
    - cat test/results.md
  artifacts:
    paths:
      - test/results.md
