test_communication:
  stage: test
  tags:
    - linux
    - ecu
  script:
    - echo " Starting ECU2 (receiver) in background..."
    - sudo ip netns exec ecu2 $(pwd)/ecu2 &
    - ECU2_PID=$!
    - echo " Running ECU1 (sender)..."
    - sudo ip netns exec ecu1 $(pwd)/ecu1 &
    - ECU1_PID=$!
    - echo " Letting them run for 5 seconds..."
    - sleep 5
    - echo " Stopping ECU programs..."
    - sudo kill $ECU1_PID || echo "ECU1 already exited"
    - sudo kill $ECU2_PID || echo "ECU2 already exited"
  needs:
    - setup_network
    - build_ecus

